### ISSUE TITLE
Change to Const

### ISSUE THREAD

**Issue by donovanclarke** [kunalkendrekar115/react-component-boilerplate-cli#3]
https://github.com/kunalkendrekar115/react-component-boilerplate-cli/blob/a95e8b276143793525bc282ab8e23c37c306efb2/src/parsers/jsx-parser.js#L1-L3

I believe these can be a constant as well :)

**Comment by kunalkendrekar115** [comment]
Changed to const:   https://github.com/kunalkendrekar115/react-component-boilerplate-cli/blob/7d86ef1f2f3a8fa1e06e95d7049a0445c714bdd7/src/parsers/jsx-parser.js#L1
