### ISSUE TITLE
Please use strict equality

### ISSUE THREAD

**Issue by donovanclarke** [kunalkendrekar115/react-component-boilerplate-cli#4]
https://github.com/kunalkendrekar115/react-component-boilerplate-cli/blob/a95e8b276143793525bc282ab8e23c37c306efb2/src/cli.js#L20

We should use `===` rather then `==`

**Comment by kunalkendrekar115** [comment]
Fixed : Please check below link
https://github.com/kunalkendrekar115/react-component-boilerplate-cli/blob/7d86ef1f2f3a8fa1e06e95d7049a0445c714bdd7/src/cli.js#L15
