### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by donovanclarke** [kunalkendrekar115/react-component-boilerplate-cli#5]
https://github.com/kunalkendrekar115/react-component-boilerplate-cli/blob/a95e8b276143793525bc282ab8e23c37c306efb2/src/creator.js#L62-L63

Some small issues here, template is spelled wrong. Maybe we can come up with a better name?

Also, can we use string interpolation here? `${componentName}/index.js`

**Comment by kunalkendrekar115** [comment]
changed templaeStr to componentTemplate : https://github.com/kunalkendrekar115/react-component-boilerplate-cli/blob/7d86ef1f2f3a8fa1e06e95d7049a0445c714bdd7/src/creator.js#L11
